--!strict
local LuaLibraryName = table.freeze({
    LUA_COLIBNAME         = "coroutine",
    LUA_TABLIBNAME        = "table",
    LUA_OSLIBNAME         = "os",
    LUA_STRLIBNAME        = "string",
    LUA_BITLIBNAME        = "bit32",
    LUA_BUFFERLIBNAME     = "buffer",
    LUA_UTF8LIBNAME       = "utf8",
    LUA_MATHLIBNAME       = "math",
    LUA_DBLIBNAME         = "debug",
    LUA_VECLIBNAME        = "vector",
})
return LuaLibraryName